### ISSUE TITLE
[Bug report] Include_role does not create role/task graph instead all tasks are mapped directly to the playbook

### ISSUE THREAD

**Issue by cvernooy23** [haidaraM/ansible-playbook-grapher#22] opened 2019-11-05 14:00 UTC
**Describe the bug**
Include_role does not seem to be detected as a "role" for the graph. A flat execution structure of playbook --> tasks is created despite all of the tasks being included in roles

**To Reproduce**
write a playbook with `include_role` instead of the roles directive. 

**Expected behavior**
I would expect the same mapping of playbook --> role --> tasks as using the role direective

**Versions:**
Outputs of :
 - ansible-version: ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/cvernooy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.5_1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.5 (default, Nov  1 2019, 02:16:32) [Clang 11.0.0 (clang-1100.0.33.8)]
    
 - ansible-playbook-grapher --version: ansible-playbook-grapher 0.9.1 (with ansible 2.8.4)

**Comment by haidaraM** [comment] 2019-11-08 13:01
I think this is the expected behavior since the `include_role` is handled as a task (https://docs.ansible.com/ansible/latest/modules/include_role_module.html#include-role-module). 

So when parsing the playbook, the included role is not part of the list of roles to be executed. This is why you don't see it as a role in the graph. Only the explicit roles (roles in `roles` block) are marked as such in the graph.

Internally (in Ansible codebase), the class `IncludeRole` that corresponds to the `include_role` is a subclass of `Task`.

**Comment by haidaraM** [comment] 2020-11-18 19:43
Hi. I'm refactoring the code base at the moment. After that, I will take a closer look to implement this feature because it can't be easily added now.

**Closed** 2021-09-15 20:29 UTC
Labels: feature-request

**Comment by haidaraM** [comment] 2021-09-15 20:35
This should have been fixed in #82 . Can you test the latest dev version : `pip install ansible-playbook-grapher==1.0.0.dev0`
